# Generated by Django 5.0.6 on 2024-05-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_loginmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
